---
# 单次任务循环时间
EVINA_SETTINGS__SLEEP = 300
# 录像单文件时间限制，单位（秒）超过此大小分段下载，如需使用大小分段请注释此字段
EVINA_SETTINGS__TIME = 3600
# 视频格式，默认为.flv。 .ts格式为 MPEGTS ， .mp4格式为 H264
EVINA_SETTINGS__SCHEME = MPEGTS
# 解码线程
EVINA_SETTINGS__THREAD = 5
# ultrafast（转码速度最快，视频往往也最模糊）、superfast、veryfast、faster、fast、medium、slow、slower、veryslow、placebo这10个选项，从快到慢。
EVINA_SETTINGS__PRESET = ultrafast
# 此选择为false时仅保存直播源链接
EVINA_SETTINGS__OPEN = false
# 使用配置的 docker 环境执行
EVINA_SETTINGS__DOCKER = false
# 文件保存路径
EVINA_SETTINGS__FILE = /home/code/evina
# nodejs安装路径
EVINA_SETTINGS__NODEJS = /usr/bin/node
# nodejs包路径
EVINA_SETTINGS__NODE_MODULES = /usr/lib/node_modules
# 接收阿里云盘登录二维码的邮箱
EVINA_SETTINGS__EMAIL_USER = '1933990359@qq.com'
# 接收阿里云盘登录二维码邮箱的STMP授权码
EVINA_SETTINGS__EMAIL_PASSWORD = 'zbkzfddntjdicdhi'






