name: evina start
on: 
  schedule: 
    - cron: '*/7 * * * *'

env: 
  TZ: Asia/Shanghai
  DOUYIN-COOKIES: ${{ secrets.DOUYIN_COOKIES }}

jobs:
  my-job:
    name: running
    runs-on: ubuntu-latest
    steps: 
      - name: checkout actions
        uses: actions/checkout@v3

      - name: set up ffmpeg
        run: |
          tar xvf ./ffm/ffmpeg-n6.0-latest-linux64-gpl-6.0.tar.xz
          sudo ln -s $PWD/ffmpeg-n6.0-latest-linux64-gpl-6.0/bin/ffmpeg /bin/ffmpeg
          rm -rf ffm

      - name: set up python 3.9
        uses: actions/setup-python@v4
        with: 
          python-version : '3.9'

      - name: set up node 14.8
        uses: actions/setup-node@v3
        with:
          node-version: '14.8'
      - name: running
        run: |
          mkdir -p ~/.aligo/
          git config --local user.email "1933990359@qq.com"
          git config --local user.name "soft-cute"
          cat >> ~/.aligo/aligo.json << EOF
          ${{ secrets.ALIGO_TOKEN }}
          EOF
          npm install -g crypto-js
          pip install requests faker dynaconf loguru python-box[all] aligo PyExecJS
          python ./evina/check.py 2>&1 | tee evina.log
          python ./evina/ffm.py