name: evina start
on: push
  # schedule: 
  #   - cron: '*/7 * * * *'

env: 
  TZ: Asia/Shanghai
  DOUYIN-COOKIES: ${{ secrets.DOUYIN_COOKIES }}

jobs:
  my-job:
    name: running
    runs-on: ubuntu-latest
    steps: 
      - name: checkout actions
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: set up python 3.9
        uses: actions/setup-python@v4
        with: 
          python-version : '3.9'

      - name: set up node 14.8
        uses: actions/setup-node@v3
        with:
          node-version: '14.8'
      - name: running
        run: |
          mkdir -p ~/.aligo/
          echo ${{ secrets.ALIGO_TOKEN}} > ~/.aligo/aligo.json
          npm install -g crypto-js
          pip install requests faker dynaconf loguru python-box[all] aligo
          python ./evina/check.py 2>&1 | tee evina.log
          ls -a
          git config --local user.email "1933990359@qq.com"
          git config --local user.name "softcute"
          python ./evina/ffm.py
      #     git commit -a -m "Add changes"
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.github_token }}
      #     branch: ${{ github.ref }}